server.port=8086
spring.application.name=api-gateway

uac.grpc.host=localhost
uac.grpc.port=50051

service.content.url=http://localhost:8081
service.quiz.url=http://localhost:8082


logging.level.com.engbridge.gateway=DEBUG
logging.level.io.grpc=DEBUG