-- Generated by Oracle SQL Developer Data Modeler 24.3.0.240.1210
--   at:        2025-11-11 22:55:42 EET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE courses (
    id_cs         NUMBER(3) NOT NULL,
    order_num_cs  NUMBER(3) NOT NULL,
    title         VARCHAR2(250) NOT NULL,
    levels_id_lvl NUMBER(3) NOT NULL
);

ALTER TABLE courses ADD CONSTRAINT courses_pk PRIMARY KEY ( id_cs,
                                                            levels_id_lvl );

CREATE TABLE exercises (
    id_ex                          NUMBER(3) NOT NULL,
    order_num_ex                   NUMBER(3),
    ex_type                        VARCHAR2(10),
    content                        CLOB,
    sections_id_sect               NUMBER(3) NOT NULL,
    sections_courses_id_cs         NUMBER(3) NOT NULL,
    sections_courses_levels_id_lvl NUMBER(3) NOT NULL
);

ALTER TABLE exercises
    ADD CONSTRAINT exercises_pk
        PRIMARY KEY ( id_ex,
                      sections_id_sect,
                      sections_courses_id_cs,
                      sections_courses_levels_id_lvl );

CREATE TABLE levels (
    id_lvl NUMBER(3) NOT NULL,
    name   VARCHAR2(2) NOT NULL
);

ALTER TABLE levels ADD CONSTRAINT levels_pk PRIMARY KEY ( id_lvl );

ALTER TABLE levels ADD CONSTRAINT levels_name_un UNIQUE ( name );

CREATE TABLE sections (
    id_sect               NUMBER(3) NOT NULL,
    order_num_sc          NUMBER(3),
    type                  VARCHAR2(15),
    courses_id_cs         NUMBER(3) NOT NULL,
    courses_levels_id_lvl NUMBER(3) NOT NULL
);

ALTER TABLE sections
    ADD CONSTRAINT sections_type_ck
        CHECK ( type IN ( 'Listening', 'Reading', 'Speaking', 'Writing' ) );

ALTER TABLE sections
    ADD CONSTRAINT sections_pk PRIMARY KEY ( id_sect,
                                             courses_id_cs,
                                             courses_levels_id_lvl );

CREATE TABLE userprogress (
    id_usrprg             NUMBER(3) NOT NULL,
    status                VARCHAR2(15),
    score                 NUMBER(5, 2),
    courses_id_cs         NUMBER(3) NOT NULL,
    courses_levels_id_lvl NUMBER(3) NOT NULL,
    users_id_user         NUMBER(3) NOT NULL
);

ALTER TABLE userprogress
    ADD CONSTRAINT userprg_status_ck
        CHECK ( status IN ( 'completed', 'in_progress', 'not_completed' ) );

ALTER TABLE userprogress
    ADD CONSTRAINT userprogress_pk
        PRIMARY KEY ( id_usrprg,
                      courses_id_cs,
                      courses_levels_id_lvl,
                      users_id_user );

CREATE TABLE users (
    id_user       NUMBER(3) NOT NULL,
    username      VARCHAR2(20) NOT NULL,
    password      VARCHAR2(50) NOT NULL,
    email         VARCHAR2(250) NOT NULL,
    role          VARCHAR2(5),
    levels_id_lvl NUMBER(3) NOT NULL
);

ALTER TABLE users
    ADD CONSTRAINT users_email_ck CHECK ( REGEXP_LIKE ( email,
                                                        '[a-z0-9._%-]+@[a-z0-9._%-]+\.[a-z]{2,4}' ) );

ALTER TABLE users
    ADD CONSTRAINT users_role_ck CHECK ( role IN ( 'ADMIN', 'USER' ) );

ALTER TABLE users ADD CONSTRAINT users_pk PRIMARY KEY ( id_user );

ALTER TABLE users ADD CONSTRAINT users_username_email_un UNIQUE ( username,
                                                                  email );

ALTER TABLE courses
    ADD CONSTRAINT courses_levels_fk FOREIGN KEY ( levels_id_lvl )
        REFERENCES levels ( id_lvl );

ALTER TABLE exercises
    ADD CONSTRAINT exercises_sections_fk
        FOREIGN KEY ( sections_id_sect,
                      sections_courses_id_cs,
                      sections_courses_levels_id_lvl )
            REFERENCES sections ( id_sect,
                                  courses_id_cs,
                                  courses_levels_id_lvl );

ALTER TABLE sections
    ADD CONSTRAINT sections_courses_fk
        FOREIGN KEY ( courses_id_cs,
                      courses_levels_id_lvl )
            REFERENCES courses ( id_cs,
                                 levels_id_lvl );

ALTER TABLE userprogress
    ADD CONSTRAINT userprogress_courses_fk
        FOREIGN KEY ( courses_id_cs,
                      courses_levels_id_lvl )
            REFERENCES courses ( id_cs,
                                 levels_id_lvl );

ALTER TABLE userprogress
    ADD CONSTRAINT userprogress_users_fk FOREIGN KEY ( users_id_user )
        REFERENCES users ( id_user );

ALTER TABLE users
    ADD CONSTRAINT users_levels_fk FOREIGN KEY ( levels_id_lvl )
        REFERENCES levels ( id_lvl );

CREATE SEQUENCE courses_id_cs_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER courses_id_cs_trg BEFORE
    INSERT ON courses
    FOR EACH ROW
    WHEN ( new.id_cs IS NULL )
BEGIN
    :new.id_cs := courses_id_cs_seq.nextval;
END;
/

CREATE SEQUENCE exercises_id_ex_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER exercises_id_ex_trg BEFORE
    INSERT ON exercises
    FOR EACH ROW
    WHEN ( new.id_ex IS NULL )
BEGIN
    :new.id_ex := exercises_id_ex_seq.nextval;
END;
/

CREATE SEQUENCE levels_id_lvl_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER levels_id_lvl_trg BEFORE
    INSERT ON levels
    FOR EACH ROW
    WHEN ( new.id_lvl IS NULL )
BEGIN
    :new.id_lvl := levels_id_lvl_seq.nextval;
END;
/

CREATE SEQUENCE sections_id_sect_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER sections_id_sect_trg BEFORE
    INSERT ON sections
    FOR EACH ROW
    WHEN ( new.id_sect IS NULL )
BEGIN
    :new.id_sect := sections_id_sect_seq.nextval;
END;
/

CREATE SEQUENCE userprogress_id_usrprg_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER userprogress_id_usrprg_trg BEFORE
    INSERT ON userprogress
    FOR EACH ROW
    WHEN ( new.id_usrprg IS NULL )
BEGIN
    :new.id_usrprg := userprogress_id_usrprg_seq.nextval;
END;
/

CREATE SEQUENCE users_id_user_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER users_id_user_trg BEFORE
    INSERT ON users
    FOR EACH ROW
    WHEN ( new.id_user IS NULL )
BEGIN
    :new.id_user := users_id_user_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             0
-- ALTER TABLE                             18
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           6
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          6
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
