# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11protos/auth.proto\x12\x04\x61uth\"R\n\x0fRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\"4\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"-\n\rLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\" \n\x0fValidateRequest\x12\r\n\x05token\x18\x01 \x01(\t\"0\n\x10ValidateResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\"\n\x11InvalidateRequest\x12\r\n\x05token\x18\x01 \x01(\t\"4\n\x12InvalidateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\x88\x02\n\x0b\x41uthService\x12;\n\x08Register\x12\x15.auth.RegisterRequest\x1a\x16.auth.RegisterResponse\"\x00\x12\x32\n\x05Login\x12\x12.auth.LoginRequest\x1a\x13.auth.LoginResponse\"\x00\x12@\n\rValidateToken\x12\x15.auth.ValidateRequest\x1a\x16.auth.ValidateResponse\"\x00\x12\x46\n\x0fInvalidateToken\x12\x17.auth.InvalidateRequest\x1a\x18.auth.InvalidateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=27
  _globals['_REGISTERREQUEST']._serialized_end=109
  _globals['_REGISTERRESPONSE']._serialized_start=111
  _globals['_REGISTERRESPONSE']._serialized_end=163
  _globals['_LOGINREQUEST']._serialized_start=165
  _globals['_LOGINREQUEST']._serialized_end=215
  _globals['_LOGINRESPONSE']._serialized_start=217
  _globals['_LOGINRESPONSE']._serialized_end=262
  _globals['_VALIDATEREQUEST']._serialized_start=264
  _globals['_VALIDATEREQUEST']._serialized_end=296
  _globals['_VALIDATERESPONSE']._serialized_start=298
  _globals['_VALIDATERESPONSE']._serialized_end=346
  _globals['_INVALIDATEREQUEST']._serialized_start=348
  _globals['_INVALIDATEREQUEST']._serialized_end=382
  _globals['_INVALIDATERESPONSE']._serialized_start=384
  _globals['_INVALIDATERESPONSE']._serialized_end=436
  _globals['_AUTHSERVICE']._serialized_start=439
  _globals['_AUTHSERVICE']._serialized_end=703
# @@protoc_insertion_point(module_scope)
